name: aws_covid_care
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.1
  feather_icons_flutter: ^4.7.4
  http: ^0.12.2
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  smooth_page_indicator: ^0.2.0
  shared_preferences: ^0.5.8
  flutter_phoenix: ^0.1.0
  font_awesome_flutter: ^8.8.1
  geolocator: ^5.3.2+2
  workmanager: ^0.2.0
  flutter_local_notifications: "1.3.0"
  provider:
  carousel_slider: ^2.2.1
  flutter_staggered_animations: "^0.1.2"
  cache_image: "^1.0.5"
  image_fade: ^0.2.1
  flutter_spinkit: "^4.1.2"
  shimmer: ^1.1.1
  webview_flutter: ^0.3.22+1
  transparent_image: ^1.0.0
  fl_chart: ^0.8.7
  country_list_pick: ^1.0.0+5
  intl: ">=0.14.0"
  dart_numerics: "^0.0.5"
  built_path: ^0.1.0
  built_path_annotations: ^0.1.0
  charts_flutter: 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "^1.7.4"
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/app_icon.png"
  image_path_android: "assets/icons/app_icon_final.png"
  adaptive_icon_background: "assets/icons/app_icon_bg.png"
  adaptive_icon_foreground: "assets/icons/app_icon_final.png"


dependency_overrides:
  analyzer: ^0.39.4
  build: ^1.2.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: 'Open Sans'
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900

    - family: 'Open Sans'
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 200
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 900

